test:
  sessions:
    default:
      database: foinz_test
      hosts:
        - localhost:27017
development:
  sessions:
    default:
      database: foinz_development
      hosts:
        - localhost:27017

